-- ============================================================
-- 🇦🇪 فخورون بالإمارات - Complete Database Schema
-- ============================================================
-- Run this entire SQL in Supabase SQL Editor
-- This will create ALL tables, RLS policies, functions, and storage buckets
-- ============================================================

-- ============================================================
-- 1. CREATE ALL TABLES
-- ============================================================

-- Posts table with all columns
CREATE TABLE IF NOT EXISTS public.posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_name TEXT NOT NULL CHECK (char_length(student_name) >= 2),
  title TEXT NOT NULL CHECK (char_length(title) >= 3),
  content TEXT NOT NULL CHECK (char_length(content) >= 1),
  category TEXT NOT NULL CHECK (category = ANY (ARRAY['video'::text, 'design'::text, 'poem'::text, 'story'::text, 'free'::text, 'powerpoint'::text])),
  image_url TEXT,
  video_url TEXT,
  document_url TEXT,
  emirate TEXT DEFAULT 'دبي' CHECK (emirate = ANY (ARRAY['أبوظبي'::text, 'دبي'::text, 'الشارقة'::text, 'عجمان'::text, 'أم القيوين'::text, 'رأس الخيمة'::text, 'الفجيرة'::text])),
  likes INTEGER NOT NULL DEFAULT 0,
  teacher_rating INTEGER DEFAULT 0,
  is_teacher_choice BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments table
CREATE TABLE IF NOT EXISTS public.comments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL CHECK (char_length(student_name) >= 2),
  content TEXT NOT NULL CHECK (char_length(content) >= 3),
  is_teacher BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- App settings table
CREATE TABLE IF NOT EXISTS public.app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT NOT NULL UNIQUE,
  setting_value BOOLEAN NOT NULL DEFAULT false,
  description TEXT,
  last_updated_by TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Post likes tables
CREATE TABLE IF NOT EXISTS public.post_likes_audit (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE(post_id, user_hash)
);

CREATE TABLE IF NOT EXISTS public.post_likes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  student_name TEXT,
  actor_name TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- User avatars table
CREATE TABLE IF NOT EXISTS public.user_avatars (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_name TEXT NOT NULL UNIQUE,
  avatar_parts JSONB DEFAULT '{}'::jsonb,
  total_likes INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Creative rooms table
CREATE TABLE IF NOT EXISTS public.creative_rooms (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_name TEXT NOT NULL UNIQUE,
  room_theme TEXT DEFAULT 'default',
  featured_works JSONB DEFAULT '[]'::jsonb,
  visitor_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Creative signatures table
CREATE TABLE IF NOT EXISTS public.creative_signatures (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_name TEXT NOT NULL UNIQUE,
  signature_type TEXT,
  signature_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Personal museums table
CREATE TABLE IF NOT EXISTS public.personal_museums (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_name TEXT NOT NULL UNIQUE,
  featured_works JSONB DEFAULT '[]'::jsonb,
  museum_theme TEXT DEFAULT 'classic',
  visitor_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Advertise requests table
CREATE TABLE IF NOT EXISTS public.advertise_requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  requester_name TEXT NOT NULL,
  organization TEXT NOT NULL,
  email TEXT NOT NULL,
  package_type TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Site stats view
CREATE OR REPLACE VIEW public.site_stats AS
SELECT
  count(*) as total_posts,
  count(distinct student_name) as total_students,
  sum(likes) as total_likes
FROM public.posts;

-- ============================================================
-- 2. ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creative_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creative_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personal_museums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertise_requests ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 3. CREATE POLICIES
-- ============================================================

-- Posts policies
CREATE POLICY "Allow public read access on posts" ON public.posts
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public insert access on posts" ON public.posts
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Comments policies
CREATE POLICY "Allow public read access on comments" ON public.comments
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public insert access on comments" ON public.comments
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- App settings policies (admin only)
CREATE POLICY "Allow admin read access on app_settings" ON public.app_settings
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow admin insert/update on app_settings" ON public.app_settings
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Likes policies
CREATE POLICY "Allow public read audit" ON public.post_likes_audit
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert audit" ON public.post_likes_audit
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read likes" ON public.post_likes
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert likes" ON public.post_likes
  FOR INSERT WITH CHECK (true);

-- Notifications policies
CREATE POLICY "Allow public read for notifications" ON public.notifications
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow system insert for notifications" ON public.notifications
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- User avatars policies
CREATE POLICY "Allow public read avatars" ON public.user_avatars
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update avatars" ON public.user_avatars
  FOR ALL USING (true) WITH CHECK (true);

-- Creative rooms policies
CREATE POLICY "Allow public read creative rooms" ON public.creative_rooms
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update creative rooms" ON public.creative_rooms
  FOR ALL USING (true) WITH CHECK (true);

-- Creative signatures policies
CREATE POLICY "Allow public read creative signatures" ON public.creative_signatures
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update creative signatures" ON public.creative_signatures
  FOR ALL USING (true) WITH CHECK (true);

-- Personal museums policies
CREATE POLICY "Allow public read personal museums" ON public.personal_museums
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update personal museums" ON public.personal_museums
  FOR ALL USING (true) WITH CHECK (true);

-- Advertise requests policies
CREATE POLICY "Allow public insert advertise requests" ON public.advertise_requests
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow admin read advertise requests" ON public.advertise_requests
  FOR SELECT TO anon, authenticated USING (true);

-- ============================================================
-- 4. CREATE FUNCTIONS
-- ============================================================

-- Like functions
CREATE OR REPLACE FUNCTION public.like_post(p_post_id UUID, p_user_hash TEXT)
RETURNS TEXT AS $$
BEGIN
  INSERT INTO public.post_likes_audit (post_id, user_hash)
  VALUES (p_post_id, p_user_hash);

  UPDATE public.posts
  SET likes = likes + 1
  WHERE id = p_post_id;

  RETURN 'LIKE_ADDED';
EXCEPTION WHEN unique_violation THEN
  RETURN 'ALREADY_LIKED';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.add_multiple_like(p_post_id UUID, p_user_hash TEXT)
RETURNS TEXT AS $$
BEGIN
  INSERT INTO public.post_likes (post_id, user_hash)
  VALUES (p_post_id, p_user_hash);

  UPDATE public.posts
  SET likes = likes + 1
  WHERE id = p_post_id;

  RETURN 'LIKE_ADDED';
EXCEPTION WHEN OTHERS THEN
  RETURN 'ERROR';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Notification function
CREATE OR REPLACE FUNCTION notify_on_comment()
RETURNS TRIGGER AS $$
DECLARE
    v_student_name TEXT;
BEGIN
    SELECT student_name INTO v_student_name FROM public.posts WHERE id = NEW.post_id;

    INSERT INTO public.notifications (post_id, type, message, student_name, actor_name)
    VALUES (
        NEW.post_id,
        'comment',
        'قام ' || NEW.student_name || ' بالتعليق على مشاركتك!',
        v_student_name,
        NEW.student_name
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- 5. CREATE TRIGGERS
-- ============================================================

DROP TRIGGER IF EXISTS tr_notify_on_comment ON public.comments;
CREATE TRIGGER tr_notify_on_comment
AFTER INSERT ON public.comments
FOR EACH ROW EXECUTE FUNCTION notify_on_comment();

-- ============================================================
-- 6. CREATE INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_category ON public.posts (category);
CREATE INDEX IF NOT EXISTS idx_posts_emirate ON public.posts (emirate);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments (post_id);
CREATE INDEX IF NOT EXISTS idx_notifications_post_id ON public.notifications (post_id);

-- ============================================================
-- 7. CREATE STORAGE BUCKETS
-- ============================================================

-- Post images bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('post-images', 'post-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access for post-images"
ON storage.objects FOR SELECT
USING (bucket_id = 'post-images');

CREATE POLICY "Allow public upload for post-images"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'post-images');

-- Post videos bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('post-videos', 'post-videos', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access for post-videos"
ON storage.objects FOR SELECT
USING (bucket_id = 'post-videos');

CREATE POLICY "Allow public upload for post-videos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'post-videos');

-- Post documents bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('post-documents', 'post-documents', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access for post-documents"
ON storage.objects FOR SELECT
USING (bucket_id = 'post-documents');

CREATE POLICY "Allow public upload for post-documents"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'post-documents');

-- ============================================================
-- 8. GRANT PERMISSIONS
-- ============================================================

GRANT SELECT, INSERT ON public.posts TO anon, authenticated;
GRANT SELECT, INSERT ON public.comments TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.app_settings TO anon, authenticated;
GRANT SELECT, INSERT ON public.post_likes_audit TO anon, authenticated;
GRANT SELECT, INSERT ON public.post_likes TO anon, authenticated;
GRANT SELECT, INSERT ON public.notifications TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.user_avatars TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.creative_rooms TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.creative_signatures TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.personal_museums TO anon, authenticated;
GRANT SELECT, INSERT ON public.advertise_requests TO anon, authenticated;

GRANT SELECT ON public.site_stats TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.like_post(UUID, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.add_multiple_like(UUID, TEXT) TO anon, authenticated;

-- ============================================================
-- 9. INSERT DEFAULT APP SETTINGS
-- ============================================================

INSERT INTO public.app_settings (setting_key, setting_value, description) VALUES
('multiple_likes_enabled', false, 'Allow users to like posts multiple times')
ON CONFLICT (setting_key) DO NOTHING;

-- ============================================================
-- ✅ Complete Database Setup Finished!
-- ============================================================